In [13]:
import pandas as pd
df = pd.read_csv("C:\\college_recommendation_system\\CleanData\\cleaned_tgeapcet_2017_2024.csv")
df.head()

,inst_code,institute_name,branch_code,branch_name,co_education,college_type,year_of_estab,place,dist_code,year,cutoff,category,gender
0,AARM,AAR MAHAVEER ENGINEERING COLLEGE,CSE,computer science and engineering,COED,PVT,2010.0,BANDLAGUDA,HYD,2017,26907.0,OC,Boys
1,AARM,AAR MAHAVEER ENGINEERING COLLEGE,ECE,electronics and communication engineering,COED,PVT,2010.0,BANDLAGUDA,HYD,2017,33871.0,OC,Boys
2,AARM,AAR MAHAVEER ENGINEERING COLLEGE,EEE,electrical and electronics engineering,COED,PVT,2010.0,BANDLAGUDA,HYD,2017,39938.0,OC,Boys
3,AARM,AAR MAHAVEER ENGINEERING COLLEGE,MEC,mechanical engineering,COED,PVT,2010.0,BANDLAGUDA,HYD,2017,38774.0,OC,Boys
4,ACEG,A C E ENGINEERING COLLEGE,CIV,civil engineering,COED,PVT,2007.0,GHATKESAR,MDL,2017,33769.0,OC,Boys

In [14]:

df["category_gender"] = (
    df["category"].astype(str) + "_" + df["gender"].astype(str)
)

print(df.columns)
df.isnull().sum()
# Drop college_type and year_of_estab columns
df = df.drop(columns=["college_type", "year_of_estab"])
df.isnull().sum()
# Remove extra spaces
df["co_education"] = df["co_education"].str.strip()
df["category"] = df["category"].str.strip()

# Convert to uppercase
df["co_education"] = df["co_education"].str.upper()
df["category"] = df["category"].str.upper()

from sklearn.preprocessing import LabelEncoder

le_college = LabelEncoder()
df["inst_code"] = le_college.fit_transform(df["inst_code"])

le_branch = LabelEncoder()
df["branch_code"] = le_branch.fit_transform(df["branch_code"])

df["category"] = df["category"].fillna("EWS")

category_map = {
    "OC":0,
    "BC_A":1,
    "BC_B":2,
    "BC_C":3,
    "BC_D":4,
    "BC_E":5,
    "SC":6,
    "ST":7,
    "EWS":8
}

df["category"] = df["category"].map(category_map)

gender_map = {
    "COED":0,
    "GIRLS":1
}

df["co_education"] = df["co_education"].map(gender_map)

le_location = LabelEncoder()
df["dist_code"] = le_location.fit_transform(df["dist_code"])

gender_map = {
    "Boys": 0,
    "Girls": 1
}

df["gender"] = df["gender"].map(gender_map)

df = df.drop(columns=[
    "institute_name",
    "branch_name",
    "category",
    "gender",
    "place"
])

df["category_gender"] = df["category_gender"].str.strip().str.upper()

from sklearn.preprocessing import LabelEncoder

le_catgen = LabelEncoder()
df["catgen_id"] = le_catgen.fit_transform(df["category_gender"])

df = df.drop(columns=["category_gender"])

df.head()

Index(['inst_code', 'institute_name', 'branch_code', 'branch_name',
       'co_education', 'college_type', 'year_of_estab', 'place', 'dist_code',
       'year', 'cutoff', 'category', 'gender', 'category_gender'],
      dtype='object')

   inst_code  branch_code  co_education  dist_code  year   cutoff  catgen_id
0          0           20             0          2  2017  26907.0         12
1          0           30             0          2  2017  33871.0         12
2          0           33             0          2  2017  39938.0         12
3          0           46             0          2  2017  38774.0         12
4          1           13             0         11  2017  33769.0         12

In [ ]:
# Save college encoder
with open(r"C:\\college_recommendation_system\\Model\\le_college.pkl", "wb") as f:
    pickle.dump(le_college, f)

# Save branch encoder
with open(r"C:\\college_recommendation_system\\Model\\le_branch.pkl", "wb") as f:
    pickle.dump(le_branch, f)

# Save location encoder
with open(r"C:\\college_recommendation_system\\Model\\le_location.pkl", "wb") as f:
    pickle.dump(le_location, f)

# Save category-gender encoder
with open(r"C:\\college_recommendation_system\\Model\\le_catgen.pkl", "wb") as f:
    pickle.dump(le_catgen, f)